[package]
name = "crud_tuple_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.11.0", features = ["macros"] }
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
